Controllers/FiberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using FiberConnectionClient.Models;
using Microsoft.AspNetCore.Mvc;
using JWT;
using Newtonsoft.Json;
using System.Text;

namespace FiberConnectionClient.Controllers
{
    public class FiberController : Controller
    {
        [HttpGet]
        public IActionResult UpdatePlan()
        {
            string AdminExp = HttpContext.Request.Cookies["AdminExpiry"];
            string AdminToken = HttpContext.Request.Cookies["AdminToken"];
            if (Convert.ToDateTime(AdminExp) < DateTime.Now)
            {
                return RedirectToAction("AdminLogin", "Admin");

            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UpdatePlan(FiberPlan fp)
        {
            string AdminToken = HttpContext.Request.Cookies["AdminToken"];
            using (var client =new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", AdminToken);
                StringContent addfp = new StringContent(JsonConvert.SerializeObject(fp), Encoding.UTF8, "application/json");
                var res = await client.PostAsync("https://fiberplanapiteam3.azurewebsites.net/api/Fiber", addfp);
                if (res.IsSuccessStatusCode)
                {
                    return RedirectToAction("AdminControlPlanDetails");
                }
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> AdminControlPlanDetails()
        {
            string AdminExp = HttpContext.Request.Cookies["AdminExpiry"];
            string AdminToken = HttpContext.Request.Cookies["AdminToken"];
            if (Convert.ToDateTime(AdminExp) < DateTime.Now)
            {
                return RedirectToAction("AdminLogin", "Admin");

            }
            List<FiberPlan> fpp = new List<FiberPlan>();
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", AdminToken);
                var res = await client.GetAsync("https://fiberplanapiteam3.azurewebsites.net/api/Fiber");
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    fpp = JsonConvert.DeserializeObject<List<FiberPlan>>(result);
                }
                return View(fpp);
            }
        }
        [HttpGet]
        public async Task<IActionResult> PlanDetails()
        {
            List<FiberPlan> fpp = new List<FiberPlan>();
            using (var client = new HttpClient())
            {
                var res = await client.GetAsync("https://fiberplanapiteam3.azurewebsites.net/api/Fiber");
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    fpp = JsonConvert.DeserializeObject<List<FiberPlan>>(result);

                }
                return View(fpp);
            }

        }
        [HttpGet]
        public async Task<IActionResult> AdminControlEditPlan(int id)
        {
            string AdminExp = HttpContext.Request.Cookies["AdminExpiry"];
            string AdminToken = HttpContext.Request.Cookies["AdminToken"];
            if (Convert.ToDateTime(AdminExp) < DateTime.Now)
            {
                return RedirectToAction("AdminLogin", "Admin");

            }
            FiberPlan fp = new FiberPlan();
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", AdminToken);
                var res = await client.GetAsync("https://fiberplanapiteam3.azurewebsites.net/api/Fiber/" + id);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    fp = JsonConvert.DeserializeObject<FiberPlan>(result);

                }
                return View(fp);
            }
        }
        [HttpPost]
        public async Task<IActionResult> AdminControlEditPlan(int id, FiberPlan fp)
        {
            string AdminExp = HttpContext.Request.Cookies["AdminExpiry"];
            if (Convert.ToDateTime(AdminExp) < DateTime.Now)
            {
                return RedirectToAction("AdminLogin", "Admin");

            }
            string AdminToken = HttpContext.Request.Cookies["AdminToken"];
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", AdminToken);
                StringContent editfp = new StringContent(JsonConvert.SerializeObject(fp), Encoding.UTF8, "application/json");
                var res = await client.PutAsync("https://fiberplanapiteam3.azurewebsites.net/api/Fiber?id=" + id, editfp);
                if (res.IsSuccessStatusCode)
                {
                    return RedirectToAction("AdminControlPlanDetails");
                }
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> AdminControlDeletePlan(int id)
        {

            string AdminToken = HttpContext.Request.Cookies["AdminToken"];
            string AdminExp = HttpContext.Request.Cookies["AdminExpiry"];
            if (Convert.ToDateTime(AdminExp) < DateTime.Now)
            {
                return RedirectToAction("AdminLogin", "Admin");

            }
            FiberPlan fp = new FiberPlan();
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", AdminToken);
                var res = await client.GetAsync("https://fiberplanapiteam3.azurewebsites.net/api/Fiber/" + id);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    fp = JsonConvert.DeserializeObject<FiberPlan>(result);

                }
                return View(fp);
            }
        }
        [HttpPost]
        public async Task<IActionResult> AdminControlDeletePlan(int id,FiberPlan fp)
        {

                string AdminToken = HttpContext.Request.Cookies["AdminToken"];
                using (var client = new HttpClient())
                {
                    client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", AdminToken);
                    var res = await client.DeleteAsync("https://fiberplanapiteam3.azurewebsites.net/api/Fiber?id=" + id);
                    if (res.IsSuccessStatusCode)
                    {
                        return RedirectToAction("AdminControlPlanDetails");
                    }
                }
                return RedirectToAction("AdminControlPlanDetails");
        }

    }
}

Controllers/OffersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using FiberConnectionClient.Models;
using Microsoft.AspNetCore.Mvc;
using JWT;
using Newtonsoft.Json;
using System.Text;

namespace FiberConnectionClient.Controllers
{
    public class OffersController : Controller
    {
        [HttpGet]
        public IActionResult UpdateOffer()
        {
            string AdminExp = HttpContext.Request.Cookies["AdminExpiry"];
            string AdminToken = HttpContext.Request.Cookies["AdminToken"];
            if (Convert.ToDateTime(AdminExp) < DateTime.Now)
            {
                return RedirectToAction("AdminLogin", "Admin");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateOffer(Offer o)
        {
            string AdminExp = HttpContext.Request.Cookies["AdminExpiry"];
            string AdminToken = HttpContext.Request.Cookies["AdminToken"];
            if (Convert.ToDateTime(AdminExp) < DateTime.Now)
            {
                return RedirectToAction("AdminLogin", "Admin");
            }
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", AdminToken);
                StringContent addo = new StringContent(JsonConvert.SerializeObject(o), Encoding.UTF8, "application/json");
                var res = await client.PostAsync("https://offersapiteam3.azurewebsites.net/api/Offer", addo);
                if (res.IsSuccessStatusCode)
                {
                    return RedirectToAction("AdminControlOfferDetails");
                }
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> AdminControlOfferDetails()
        {
            string AdminExp = HttpContext.Request.Cookies["AdminExpiry"];
            string AdminToken = HttpContext.Request.Cookies["AdminToken"];
            if (Convert.ToDateTime(AdminExp) < DateTime.Now)
            {
                return RedirectToAction("AdminLogin", "Admin");
            }
            List<Offer> os = new List<Offer>();
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", AdminToken);
                var res = await client.GetAsync("https://offersapiteam3.azurewebsites.net/api/Offer");
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    os = JsonConvert.DeserializeObject<List<Offer>>(result);

                }
                return View(os);
            }

        }
        [HttpGet]
        public async Task<IActionResult> OfferDetails(int id)
        {
            Offer o = new Offer();
            using (var client = new HttpClient())
            {
                var res = await client.GetAsync("https://offersapiteam3.azurewebsites.net/api/Offer/" + id);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    o = JsonConvert.DeserializeObject<Offer>(result);

                }
                return View(o);
            }

        }
        [HttpGet]
        public async Task<IActionResult> AdminControlEditOffer(int id)
        {
            string AdminExp = HttpContext.Request.Cookies["AdminExpiry"];
            string AdminToken = HttpContext.Request.Cookies["AdminToken"];
            if (Convert.ToDateTime(AdminExp) < DateTime.Now)
            {
                return RedirectToAction("AdminLogin", "Admin");
            }
            Offer o = new Offer();
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", AdminToken);
                var res = await client.GetAsync("https://offersapiteam3.azurewebsites.net/api/Offer/ " + id);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    o = JsonConvert.DeserializeObject<Offer>(result);

                }
                return View(o);
            }
        }
        [HttpPost]
        public async Task<IActionResult> AdminControlEditOffer(int id,Offer o)
        {
            string AdminExp = HttpContext.Request.Cookies["AdminExpiry"];
            string AdminToken = HttpContext.Request.Cookies["AdminToken"];
            if (Convert.ToDateTime(AdminExp) < DateTime.Now)
            {
                return RedirectToAction("AdminLogin", "Admin");
            }
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", AdminToken);
                StringContent edito = new StringContent(JsonConvert.SerializeObject(o), Encoding.UTF8, "application/json");
                var res = await client.PutAsync("https://offersapiteam3.azurewebsites.net/api/Offer?id=" + id, edito);
                if (res.IsSuccessStatusCode)
                {
                    return RedirectToAction("AdminControlOfferDetails");
                }
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> AdminControlDeleteOffer(int id)
        {
            string AdminExp = HttpContext.Request.Cookies["AdminExpiry"];
            string AdminToken = HttpContext.Request.Cookies["AdminToken"];
            if (Convert.ToDateTime(AdminExp) < DateTime.Now)
            {
                return RedirectToAction("AdminLogin", "Admin");
            }
            Offer o = new Offer();
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", AdminToken);
                var res = await client.GetAsync("https://offersapiteam3.azurewebsites.net/api/Offer/" + id);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    o = JsonConvert.DeserializeObject<Offer>(result);

                }
                return View(o);
            }
        }
        [HttpPost]
        public async Task<IActionResult> AdminControlDeletePlan(int id, Offer o)
        {
            string AdminExp = HttpContext.Request.Cookies["AdminExpiry"];
            string AdminToken = HttpContext.Request.Cookies["AdminToken"];
            if (Convert.ToDateTime(AdminExp) < DateTime.Now)
            {
                return RedirectToAction("AdminLogin", "Admin");
            }
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", AdminToken);
                var res = await client.DeleteAsync("https://offersapiteam3.azurewebsites.net/api/Offer?id=" + id);
                if (res.IsSuccessStatusCode)
                {
                    return RedirectToAction("AdminControlOfferDetails");
                }
            }
            return RedirectToAction("AdminControlOfferDetails");
        }

    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FiberConnection</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Login.css" />
    <link rel="stylesheet" href="~/css/Button.css" />
    <link rel="stylesheet" href="~/css/background.css" />
</head>
<body class="bg-dark">
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-transparent">
            <a class="navbar-brand" asp-controller="Admin" asp-action="AdminControl">
                <span><img src="~/images/Logo.png" width="30" height="30" class="d-inline-block align-top" alt=""> </span>
                FlixFiber Admin Control
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">

                <partial name="_AdminLoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-transparent ">
        <div class="container text-dark">
            &copy; 2021 - FlixFiber - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_AdminLoginPartial.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-controller="Fiber" asp-action="AdminControlPlanDetails">Plans</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-controller="Offers" asp-action="AdminControlOfferDetails">Offers</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-controller="Employee" asp-action="EmployeeList">Employees</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-controller="Employee" asp-action="RegisterEmployee">Add Employees</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-controller="Customer" asp-action="CustomerList">Customers</a>
    </li>
    @{
        ViewBag.Data = HttpContextAccessor.HttpContext.Request.Cookies["AdminToken"];
    }
    @if (@ViewBag.Data != null)
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Admin" asp-action="AdminControl">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Admin" asp-action="Logout">Logout</a>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Fiber" asp-action="PlanDetails">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Customer" asp-action="CustomerLogin">UserLogin</a>
        </li>
    }
</ul>

Views/Shared/_EmployeeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FiberConnection</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Login.css" />
    <link rel="stylesheet" href="~/css/Button.css" />
    <link rel="stylesheet" href="~/css/background.css" />

</head>
<body class="bg-dark">
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-transparent">
            <a class="navbar-brand" asp-controller="Fiber" asp-action="PlanDetails">
                <span><img src="~/images/Logo.png" width="30" height="30" class="d-inline-block align-top" alt=""> </span>
                FlixFiber Employee Service
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-controller="Status" asp-action="AllStatus">Status</a>
                    </li>
                </ul>
                <partial name="_EmployeeLoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-transparent ">
        <div class="container text-dark">
            &copy; 2021 - FlixFiber - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_EmployeeLoginPartial.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<ul class="navbar-nav">
    @{
        ViewBag.Data = HttpContextAccessor.HttpContext.Session.GetString("EmpName");
    }
    @if (@ViewBag.Data != null)
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Employee" asp-action="Profile">@ViewBag.Data</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Employee" asp-action="Logout">Logout</a>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Fiber" asp-action="PlanDetails">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-controller="Customer" asp-action="CustomerLogin">UserLogin</a>
        </li>
    }
</ul>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FiberConnection</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Login.css" />
    <link rel="stylesheet" href="~/css/Button.css" />
    <link rel="stylesheet" href="~/css/background.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-transparent text-black-50">
            <a class="navbar-brand" asp-controller="Fiber" asp-action="PlanDetails">
                <span><img src="~/images/Logo.png" width="30" height="30" class="d-inline-block align-top" alt=""> </span>
                FlixFiber
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link tcolor" asp-area="" asp-controller="Fiber" asp-action="PlanDetails">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link tcolor" asp-controller="Status" asp-action="StatusList">Status</a>
                    </li>
                </ul>
                <span>  </span>
                <span>  </span>
                <span>  </span>
                <span>   </span>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>