Controllers/BillingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FiberConnectionClient.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using FiberConnectionClient.Models;
using JWT;
using JWT.Algorithms;
using JWT.Serializers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System.Net.Http;
using System.Text;

namespace FiberConnectionClient.Controllers
{
    public class BillingController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> RequestBilling(int id)
        {
            string Token = HttpContext.Request.Cookies["Token"];
            string Exp = HttpContext.Request.Cookies["Expiry"];
            if (Convert.ToDateTime(Exp) < DateTime.Now)
            {
                return RedirectToAction("CustomerLogin", "Customer");
            }
            Billing b = new Billing();
            using (var client = new HttpClient())
            {
                var res = await client.GetAsync("https://billingapiteam3.azurewebsites.net/api/Billing/" + id);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    b = JsonConvert.DeserializeObject<Billing>(result);

                }
                return View(b);
            }
        }
        [HttpPost]
        public async Task<IActionResult> RequestBilling(int id,Billing b)
        {
            string Token = HttpContext.Request.Cookies["Token"];
            string Exp = HttpContext.Request.Cookies["Expiry"];
            if (Convert.ToDateTime(Exp) < DateTime.Now)
            {
                return RedirectToAction("CustomerLogin", "Customer");
            }
            StringContent b_content = new StringContent(JsonConvert.SerializeObject(b), Encoding.UTF8, "application/json");
            using (var client = new HttpClient())
            {
                var res = await client.PutAsync("https://billingapiteam3.azurewebsites.net/api/Billing?=" + id, b_content);
                if (res.IsSuccessStatusCode)
                {
                    return RedirectToAction("PlanDetails", "Fiber");
                }
                return RedirectToAction("PlanDetails", "Fiber");
            }
        }

        [Route("BillingDetails/RequestBill/{id:int}")]
        public async Task<IActionResult> RequestBill(Billing b, int id)
        {
            string Token = HttpContext.Request.Cookies["Token"];
            string Exp = HttpContext.Request.Cookies["Expiry"];
            if (Convert.ToDateTime(Exp) < DateTime.Now)
            {
                return RedirectToAction("CustomerLogin", "Customer");
            }
            int c_id =Convert.ToInt32(HttpContext.Request.Cookies["UserId"]);
            int reqid =0;
            StringContent b_content = new StringContent(JsonConvert.SerializeObject(b), Encoding.UTF8, "application/json");
            using (var client = new HttpClient())
            {
                var res = await client.PostAsync("https://billingapiteam3.azurewebsites.net/api/Billing?id=" + id+"&c_id="+c_id, b_content);
                if (res.IsSuccessStatusCode)
                    {
                    var result = res.Content.ReadAsStringAsync().Result;
                    reqid = JsonConvert.DeserializeObject<int>(result);
                    return RedirectToAction("RequestBilling", new { id = reqid });
                }
                return RedirectToAction("PlanDetails","Fiber");
            }
        }
    }
}

Controllers/OffersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using FiberConnectionClient.Models;
using Microsoft.AspNetCore.Mvc;
using JWT;
using Newtonsoft.Json;
using System.Text;

namespace FiberConnectionClient.Controllers
{
    public class OffersController : Controller
    {
        [HttpGet]
        public IActionResult UpdateOffer()
        {
            string AdminExp = HttpContext.Request.Cookies["AdminExpiry"];
            string AdminToken = HttpContext.Request.Cookies["AdminToken"];
            if (Convert.ToDateTime(AdminExp) < DateTime.Now)
            {
                return RedirectToAction("AdminLogin", "Admin");
            }
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UpdateOffer(Offer o)
        {
            string AdminExp = HttpContext.Request.Cookies["AdminExpiry"];
            string AdminToken = HttpContext.Request.Cookies["AdminToken"];
            if (Convert.ToDateTime(AdminExp) < DateTime.Now)
            {
                return RedirectToAction("AdminLogin", "Admin");
            }
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", AdminToken);
                StringContent addo = new StringContent(JsonConvert.SerializeObject(o), Encoding.UTF8, "application/json");
                var res = await client.PostAsync("https://offersapiteam3.azurewebsites.net/api/Offer", addo);
                if (res.IsSuccessStatusCode)
                {
                    return RedirectToAction("AdminControlOfferDetails");
                }
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> AdminControlOfferDetails()
        {
            string AdminExp = HttpContext.Request.Cookies["AdminExpiry"];
            string AdminToken = HttpContext.Request.Cookies["AdminToken"];
            if (Convert.ToDateTime(AdminExp) < DateTime.Now)
            {
                return RedirectToAction("AdminLogin", "Admin");
            }
            List<Offer> os = new List<Offer>();
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", AdminToken);
                var res = await client.GetAsync("https://offersapiteam3.azurewebsites.net/api/Offer");
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    os = JsonConvert.DeserializeObject<List<Offer>>(result);

                }
                return View(os);
            }

        }
        [HttpGet]
        public async Task<IActionResult> OfferDetails(int id)
        {
            Offer o = new Offer();
            using (var client = new HttpClient())
            {
                var res = await client.GetAsync("https://offersapiteam3.azurewebsites.net/api/Offer/" + id);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    o = JsonConvert.DeserializeObject<Offer>(result);

                }
                return View(o);
            }

        }
        [HttpGet]
        public async Task<IActionResult> AdminControlEditOffer(int id)
        {
            string AdminExp = HttpContext.Request.Cookies["AdminExpiry"];
            string AdminToken = HttpContext.Request.Cookies["AdminToken"];
            if (Convert.ToDateTime(AdminExp) < DateTime.Now)
            {
                return RedirectToAction("AdminLogin", "Admin");
            }
            Offer o = new Offer();
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", AdminToken);
                var res = await client.GetAsync("https://offersapiteam3.azurewebsites.net/api/Offer/ " + id);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    o = JsonConvert.DeserializeObject<Offer>(result);

                }
                return View(o);
            }
        }
        [HttpPost]
        public async Task<IActionResult> AdminControlEditOffer(int id,Offer o)
        {
            string AdminExp = HttpContext.Request.Cookies["AdminExpiry"];
            string AdminToken = HttpContext.Request.Cookies["AdminToken"];
            if (Convert.ToDateTime(AdminExp) < DateTime.Now)
            {
                return RedirectToAction("AdminLogin", "Admin");
            }
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", AdminToken);
                StringContent edito = new StringContent(JsonConvert.SerializeObject(o), Encoding.UTF8, "application/json");
                var res = await client.PutAsync("https://offersapiteam3.azurewebsites.net/api/Offer?id=" + id, edito);
                if (res.IsSuccessStatusCode)
                {
                    return RedirectToAction("AdminControlOfferDetails");
                }
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> AdminControlDeleteOffer(int id)
        {
            string AdminExp = HttpContext.Request.Cookies["AdminExpiry"];
            string AdminToken = HttpContext.Request.Cookies["AdminToken"];
            if (Convert.ToDateTime(AdminExp) < DateTime.Now)
            {
                return RedirectToAction("AdminLogin", "Admin");
            }
            Offer o = new Offer();
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", AdminToken);
                var res = await client.GetAsync("https://offersapiteam3.azurewebsites.net/api/Offer/" + id);
                if (res.IsSuccessStatusCode)
                {
                    var result = res.Content.ReadAsStringAsync().Result;
                    o = JsonConvert.DeserializeObject<Offer>(result);

                }
                return View(o);
            }
        }
        [HttpPost]
        public async Task<IActionResult> AdminControlDeletePlan(int id, Offer o)
        {
            string AdminExp = HttpContext.Request.Cookies["AdminExpiry"];
            string AdminToken = HttpContext.Request.Cookies["AdminToken"];
            if (Convert.ToDateTime(AdminExp) < DateTime.Now)
            {
                return RedirectToAction("AdminLogin", "Admin");
            }
            using (var client = new HttpClient())
            {
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", AdminToken);
                var res = await client.DeleteAsync("https://offersapiteam3.azurewebsites.net/api/Offer?id=" + id);
                if (res.IsSuccessStatusCode)
                {
                    return RedirectToAction("AdminControlOfferDetails");
                }
            }
            return RedirectToAction("AdminControlOfferDetails");
        }

    }
}

Views/Fiber/AdminControlDeletePlan.cshtml
@model FiberConnectionClient.Models.FiberPlan

@{
    ViewData["Title"] = "AdminControlDeletePlan";
}
@{
    Layout = "_AdminLayout";
}
<style>
    .tcolor {
        color: #03e9f4;
    }

    .c1 {
        margin: 0 auto; /* Added */
        float: none; /* Added */
        margin-bottom: 10px; /* Added */
    }

    .text-n {
        color: #8a6ea7;
    }
</style>
<br />
<div class="flash">
    <h2>Are you sure you want to delete this Plan ?</h2>
</div>
<div class="card crd c1 bg-dark login-box" style="max-width: 30rem;">
    <h2>FiberPlan</h2>
    <hr />
    <div>
        <div class="card-body text-center">
            <div class="text-center text-n">
                Name : <span class="tcolor">@Html.DisplayFor(model => model.PlanName)</span>
            </div>
            <br />
            <div class="text-center text-n">
                Plan Price : <span class="tcolor">@Html.DisplayFor(model => model.PlanPrice)</span>
            </div>
            <br />
            <div class="text-center text-n">
                Plan Speed : <span class="tcolor">@Html.DisplayFor(model => model.PlanSpeed)</span>
            </div>
            <br />
            <div class="text-center text-n">
                Image : <span class="tcolor">@Html.DisplayFor(model => model.Image)</span>
            </div>
            <br />


            <form asp-action="AdminControlDeletePlan" id="f1" class="c1 flash">
                <input type="hidden" asp-for="PlanId" />
                <a href="#" onclick="document.getElementById('f1').submit();">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    Delete
                </a>
                <a asp-action="AdminControlPlanDetails">Back</a>
            </form>
        </div>
    </div>
</div>

Views/Fiber/AdminControlEditPlan.cshtml
@model FiberConnectionClient.Models.FiberPlan

@{
    ViewData["Title"] = "AdminControlEditPlan";
}
@{
    Layout = "_AdminLayout";
}
<style>
    .c1 {
        margin: 0 auto; /* Added */
        float: none; /* Added */
        margin-bottom: 10px; /* Added */
    }
</style>
<br />
<br />
<br />
<div class="card crd bg-dark mb-3 c1" style="max-width: 30rem;">
    <div class="card-body">
        <div class="login-box">
            <h2>Edit Plan</h2>
            <form id="f1" asp-action="AdminControlEditPlan">
                <div class="user-box">
                    <input asp-for="PlanId" required>
                    <label>Id</label>
                    <span asp-validation-for="PlanId" class="text-danger"></span>
                </div>
                <div class="user-box">
                    <input asp-for="PlanName" required>
                    <label>Plan Name</label>
                    <span asp-validation-for="PlanName" class="text-danger"></span>
                </div>
                <div class="user-box">
                    <input asp-for="PlanPrice" required>
                    <label>Plan Price</label>
                    <span asp-validation-for="PlanPrice" class="text-danger"></span>
                </div>
                <div class="user-box">
                    <input asp-for="PlanSpeed" required>
                    <label>Speed</label>
                    <span asp-validation-for="PlanSpeed" class="text-danger"></span>
                </div>
                <div class="user-box">
                    <input asp-for="Validity" required>
                    <label>Validity</label>
                    <span asp-validation-for="Validity" class="text-danger"></span>
                </div>
                <div class="user-box">
                    <input asp-for="OfferId" required>
                    <label>OfferId</label>
                    <span asp-validation-for="OfferId" class="text-danger"></span>
                </div>
                <div class="user-box">
                    <input asp-for="Image" required>
                    <label>Image</label>
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                <a href="#" onclick="document.getElementById('f1').submit();">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    Edit
                </a>
                <a asp-action="AdminControlPlanDetails">
                    Back
                </a>
            </form>
        </div>
    </div>
</div>

Views/Fiber/AdminControlPlanDetails.cshtml
@model IEnumerable<FiberConnectionClient.Models.FiberPlan>

@{
    ViewData["Title"] = "AdminControlPlanDetails";
}
@{
    Layout = "_AdminLayout";
}

<br />
<div class="flash">
    <h2>Plan List</h2>
</div>
<table class="table bg-dark crd">
    <thead style="color: #03e9f4;">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PlanName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlanPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlanSpeed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Validity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OfferId)
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody style="color: #8a6ea7;">
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PlanName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlanPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PlanSpeed)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Validity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Image)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OfferId)
                </td>
                <td class="flash">
                    <a  asp-action="AdminControlEditPlan" asp-route-id="@item.PlanId">Edit</a>
                    <a  asp-action="AdminControlDeletePlan" asp-route-id="@item.PlanId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Fiber/PlanDetails.cshtml
@model IEnumerable<FiberConnectionClient.Models.FiberPlan>
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

@{
    ViewData["Title"] = "PlanDetails";
}
@{
    ViewBag.Data = HttpContextAccessor.HttpContext.Request.Cookies["Expiry"];
}
<style>
    .tcolor {
        color: #03e9f4;
    }
    .card {
        margin-bottom: 20px;
    }
</style>
<br />
<div class="flash">
    <h2 style="color: snow;"><img src="~/images/Plan.png" width="40" height="40" class="d-inline-block align-top" alt=""> PlanDetails</h2>
</div>
<div class="container mt-5 mb-3 ">
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-4">
                <div class="card text-white crd bg-dark" style="width: 18rem;">
                    <img class="card-img-top" style="width:285px;height:200px;border-radius:20px;" src="@Html.DisplayFor(modelItem => item.Image)" alt="Card image cap">
                    <div class="card-body">
                        <div class="text-center">
                            <h5 class="card-title">@Html.DisplayFor(modelItem => item.PlanName)</h5>
                        </div>
                        <div class="text-center">
                            <h6 class="card-text tcolor"><span><img src="~/images/speed1.png" width="25" height="25" class="d-inline-block align-top" alt=""> </span> Plan Speed: <span class="text-white">@Html.DisplayFor(modelItem => item.PlanSpeed)</span></h6>
                        </div>
                        <br />
                        <div class="text-center">
                            <h6 class="card-text tcolor"><span><img src="~/images/validity.png" width="25" height="25" class="d-inline-block align-top" alt=""> </span> Plan Validity: <span class="text-white">@Html.DisplayFor(modelItem => item.Validity)</span></h6>
                        </div>
                        <br />
                        <div class="text-center">
                            <h6 class="card-text tcolor"><span><img src="~/images/price.png" width="25" height="25" class="d-inline-block align-top" alt=""> </span> Plan Price: <span class="text-white">₹@Html.DisplayFor(modelItem => item.PlanPrice)</span></h6>
                        </div>
                        <br />
                        <div class="text-center">
                            <h6 class="card-text tcolor"><span><img src="~/images/wifi.png" width="25" height="25" class="d-inline-block align-top" alt=""> </span> Unlimted</h6>
                        </div>
                        <br />
                        <div class="text-center">
                            <h6 class="card-text tcolor"><span><img src="~/images/free.png" width="25" height="25" class="d-inline-block align-top" alt=""> </span> 24*7 std/isd Free</h6>
                        </div>
                        <br />

                        <div class="text-center card-footer border-white flash">
                            <a asp-controller="Offers" asp-action="OfferDetails" asp-route-id="@item.OfferId" class="btn btn-outline-light"><img src="~/images/Offer.png" width="40" height="40" class="d-inline-block align-top" alt=""></a>
                        </div>
                        <br />
                        <div class="text-center card-footer border-white flash">
                            @if (Convert.ToDateTime(@ViewBag.Data) < DateTime.Now)
                            {
                                <a asp-controller="Customer" asp-action="CustomerLogin">
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                    Buy
                                </a>
                            }
                            else
                            {
                                <a asp-controller="Billing" asp-action="RequestBill" asp-route-id="@item.PlanId">
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                    Buy
                                </a>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<br />
<br />
<br />

Views/Fiber/UpdatePlan.cshtml
@model FiberConnectionClient.Models.FiberPlan

@{
    ViewData["Title"] = "UpdatePlan";
    Layout = "_AdminLayout";
}
<style>
    .c1 {
        margin: 0 auto; /* Added */
        float: none; /* Added */
        margin-bottom: 10px; /* Added */
    }
</style>
<br />
<br />
<br />
<div class="card crd bg-dark mb-3 c1" style="max-width: 30rem;">
    <div class="card-body">
        <div class="login-box">
            <h2>Add Plan</h2>
            <form id="f1" asp-action="UpdatePlan">
                <div class="user-box">
                    <input asp-for="PlanId" required>
                    <label>Id</label>
                    <span asp-validation-for="PlanId" class="text-danger"></span>
                </div>
                <div class="user-box">
                    <input asp-for="PlanName" required>
                    <label>Plan Name</label>
                    <span asp-validation-for="PlanName" class="text-danger"></span>
                </div>
                <div class="user-box">
                    <input asp-for="PlanPrice" required>
                    <label>Plan Price</label>
                    <span asp-validation-for="PlanPrice" class="text-danger"></span>
                </div>
                <div class="user-box">
                    <input asp-for="PlanSpeed" required>
                    <label>Speed</label>
                    <span asp-validation-for="PlanSpeed" class="text-danger"></span>
                </div>
                <div class="user-box">
                    <input asp-for="Validity" required>
                    <label>Validity</label>
                    <span asp-validation-for="Validity" class="text-danger"></span>
                </div>
                <div class="user-box">
                    <input asp-for="OfferId" required>
                    <label>OfferId</label>
                    <span asp-validation-for="OfferId" class="text-danger"></span>
                </div>
                <div class="user-box">
                    <input asp-for="Image" required>
                    <label>Image</label>
                    <span asp-validation-for="Image" class="text-danger"></span>
                </div>
                <a href="#" onclick="document.getElementById('f1').submit();">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    Add Plan
                </a>
                <a asp-action="AdminControl" asp-controller="Admin">
                    Back
                </a>
            </form>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}